### ISSUE TITLE
Search food recalls by keyword

### ISSUE THREAD

**Issue by adj7388** [devis/18FAgileBPA#1]
As a food consumer
I want to refine my food recall search by food type
so that my food recall search results are more relevant to what I eat

Acceptance Criteria:

* User can keyword search for recalled foods
* User does not have to resubmit their location (geo or zip) in order to keyword search

Tasks:
- [x] Modify recall API to allow search keywords @LinuxBozo
- [x] Add search field to UI @poorgeek

**Comment by poorgeek** [comment]
![18f_agile_delivery_services_bpa](https://cloud.githubusercontent.com/assets/489299/8366262/bfb32f38-1b50-11e5-9d27-90ec809ec342.jpg)

Thoughts on this mockup of the search and age filter from #8?

**Comment by adj7388** [comment]
I like it. Would it be better to say explicitly "Search by food name" instead of "keyword"?

**Comment by poorgeek** [comment]
Except that you can search against anything that might be in the product description. So you could search for "ice cream" or "ACME Foods" or "12.5 oz" if you wanted.

**Comment by LinuxBozo** [comment]
Might want more diversity in the placeholder text then? Or, maybe the label is "Search by product"?

**Comment by adj7388** [comment]
OK got it. Then maybe the examples in the input field should reflect that then "ice cream, pork rinds, ACME Foods, etc." Not a big deal. It's basically fine as-is for an MVP

**Comment by adj7388** [comment]
Or "Search Product Description" and more diverse examples

**Comment by poorgeek** [comment]
![18f_agile_delivery_services_bpa](https://cloud.githubusercontent.com/assets/489299/8366766/f648bd7a-1b54-11e5-92e7-cb45462d81c8.jpg)

Updates to the field labels and the placeholder text

**Comment by adj7388** [comment]
:+1:

**Comment by LinuxBozo** [comment]
:+1:
