### ISSUE TITLE
Configuration Management

### ISSUE THREAD

**Issue by adj7388** [devis/18FAgileBPA#10]
- [x] Set up continuous integration
- [x] Set up continuous monitoring
- [x] Set up quality metrics
- [x] Set up production hosting
- [x] Set up continuous deployment
- [x] Update readme on getting up and running locally
- [x] Update readme on how to deploy into other production systems

**Comment by mmarod** [comment]
Since me and Nick are both out of pocket until next week, Adam is going to get the ball rolling on Heroku. If it turns out that Heroku is not sufficient or that AWS is the better option, we will adjust on Monday.

**Comment by LinuxBozo** [comment]
Everything now complete.
