### ISSUE TITLE
List of food recalls for a selected state

### ISSUE THREAD

**Issue by poorgeek** [devis/18FAgileBPA#3]
As a food consumer
I want to know about food recalls in my state
So that I can avoid purchasing or consuming recalled foods

Acceptance Criteria
* App displays list of recalled food, based on their current location (state and nationwide)
* Results limited to Ongoing status and recall initiation within 6 months
* Results limited to first 100 records
* App will display these fields: product_description, reason_for_recall, code_info, recall_initiation_date

Tasks
- [x] Develop lat/long endpoint for querying food recalls @LinuxBozo 
- [x] Create wireframe for food recall results @poorgeek
- [x] Create design comp for food recall results @poorgeek
- [x] Get lat/long from browser @poorgeek
- [x] Display results @poorgeek

**Comment by poorgeek** [comment]
@LinuxBozo for displaying the data, what's the best way to display the current state? Can the `/api/recall` endpoint return that along with rest of the data since we already have it?

**Comment by LinuxBozo** [comment]
@poorgeek Yes, since we're getting the data already, I can insert into the returned json structure in the `meta` section. Do you want code (abbreviation), full name, or both? 

e.g.:
```json
{
    "meta": {
        ...

        "code": "VA",
        "name": "Virginia"
    }

   ...
}
```

**Comment by LinuxBozo** [comment]
Actually, the more I think about it, it probably makes more sense to do code only, and just go with `state` as the identifier at this point..
Something like:
```json
{
    "meta": {
        ...

        "state": "VA",
    }

   ...
}
```

**Comment by poorgeek** [comment]
I'd prefer to have the state name rather than abbr. I was planning on displaying a header for the result set like "Recent food recalls in Virginia". Why would you not want to include the name?

**Comment by LinuxBozo** [comment]
Good question. `"state": "Virginia"` it is.

**Comment by adj7388** [comment]
Done and tested in LA, TX, NC, VA, CO (and in-flight) :-)
