### ISSUE TITLE
Change wording to reinforce linkage between recalls and markets

### ISSUE THREAD

**Issue by adj7388** [devis/18FAgileBPA#42]
It's probably a ways off before we can create a linkage in the API between the food(s) in a product recall and the markets/businesses where an alternative might be available.

In the meantime, we might be able to make that linkage clearer to new users by changing the "Local Farmer Markets" button to something like:

* "You may find alternatives to recalled products at &lt;button&gt;**Farmers Markets Near You**&lt;/button&gt;."
* "Want to avoid recalled products? Shop at &lt;button&gt;**Farmers Markets Near You**&lt;/button&gt;."
* or something like that

**Comment by poorgeek** [comment]
How about something like this?
![18f_agile_delivery_services_bpa](https://cloud.githubusercontent.com/assets/489299/8387903/aeb3ee88-1c19-11e5-8802-7a0d73e3373e.jpg)

**Comment by adj7388** [comment]
:+1:
