### ISSUE TITLE
Find local replacements for recalled food by zip code

### ISSUE THREAD

**Issue by poorgeek** [devis/18FAgileBPA#7]
As a food consumer
I want to enter my zip code
So that the system can show me recalls and markets in my area

Acceptance Criteria:

* User can enter their zip code and system returns recalls and markets for the state where the zip code resides
* User can retrigger the geolocation if they do not want to enter their zip code

Tasks

- [x] Add API service for zip code lookup @LinuxBozo
- [x] Mock up new UI @LinuxBozo
- [x] Add a method to the UI for getting the user's zip code @LinuxBozo

**Comment by LinuxBozo** [comment]
**Live code mockup**
![screenshot 2015-06-25 10 46 00](https://cloud.githubusercontent.com/assets/723420/8362523/69d1ce5c-1b47-11e5-8ad4-dbf88b442866.png)

**Comment by adj7388** [comment]
May be nit-picky ... but I'm not sure it's clear how the two buttons differ. It might be reasonable to assume that you could 1. enter the Zip code, then 2. click Find Me. Or you could also 1. Enter Zip code, and 2. click Go. And what would be the difference.

Maybe a simple change: change "Go" to "Use Zip code"  and "Find Me" to "Use Geolocation"?

**Comment by LinuxBozo** [comment]
@adj7388 How about something more like this, so it's a bit more clear?

![screenshot 2015-06-25 16 25 14](https://cloud.githubusercontent.com/assets/723420/8364795/cea55af6-1b56-11e5-8186-11f55de3111c.png)

Or a bit more explicit:

![screenshot 2015-06-25 16 22 29](https://cloud.githubusercontent.com/assets/723420/8364745/7a8e3924-1b56-11e5-98e6-07798e3ff832.png)

**Comment by LinuxBozo** [comment]
@poorgeek thoughts here?

**Comment by adj7388** [comment]
I like the second one (a bit more explicit).

**Comment by poorgeek** [comment]
I don't think the 'Geolocation' label will mean anything to a user.

Maybe something like the Target example here: http://ux.stackexchange.com/a/48679 ?? Of course if we do something like that then we could drop the dialog too.

**Comment by LinuxBozo** [comment]
@adj7388 @poorgeek 

Ok, how about this then:

![screenshot 2015-06-25 16 50 39](https://cloud.githubusercontent.com/assets/723420/8365316/5a52ad9e-1b5a-11e5-9759-667b912fc616.png)

**Comment by poorgeek** [comment]
:+1:

**Comment by doelleri** [comment]
I wasn't asked but :+1: too!

**Comment by adj7388** [comment]
(thumbsup) love it
