### ISSUE TITLE
Customize date filter for food recall results

### ISSUE THREAD

**Issue by adj7388** [devis/18FAgileBPA#8]
As a user
I want to customize the date filter used to query food recalls
So that I get the recall information I need

Acceptance Criteria:
* User can select from a predefined list of date ranges what information to show by recall initiation date
* Filter contains the following options: Last month, 3 months, 6 months, year, all. The default is 3 months.

Task List:
- [x] Modify recall API service to limit results by applied filter @LinuxBozo
- [x] Create a wireframe of the filters @poorgeek
- [x] Add filter to UI @poorgeek

**Comment by poorgeek** [comment]
Docs for [filtering the FDA data by dates](https://open.fda.gov/api/reference/#dates-and-ranges)

**Comment by poorgeek** [comment]
After reviewing some of the data, we've decided to default to showing recalls with an age of 3 months, as opposed to 6 since it provides a smaller (faster) dataset in most cases.

Updating AC.
